### ISSUE TITLE
Proxy does not send register_response currently 

### ISSUE THREAD

**Issue by naderzare** [CLSFramework/soccer-simulation-proxy#32]
message BestPlannerActionRequest {
  RegisterResponse register_response = 1;
  map<int32, RpcActionState> pairs = 2;
  State state = 3;
}

**Comment by naderzare** [comment]
it seems that the proxy does not send the register_response correctly in server side planner mode

**Comment by SK2iP** [comment]
Is there a specific moment when this happened that I could check in more detail?

**Comment by SK2iP** [comment]
I found the problem. The issue is that we read the register_response from state in the Python server, but we don't set the register_response for state in the proxy. However, the other issue is that when we set the register_response for state in the proxy, we encounter a gRPC error stating that we are exceeding the maximum message size for BestPlannerActionRequest. I believe we should define the register_response only for the state object or the BestPlannerActionRequest object.
